from pyspark.sql.types import IntegerType, DateType
from pyspark.sql.types import StructType, StructField

schema = StructType([
    StructField("STN", IntegerType()),
    StructField("DATE", DateType()),
    StructField("DDVEC", IntegerType()),
    StructField("FHVEC", IntegerType()),
    StructField("FG", IntegerType()),
    StructField("FHX", IntegerType()),
    StructField("FHXH", IntegerType()),
    StructField("FHN", IntegerType()),
    StructField("FHNH", IntegerType()),
    StructField("FXX", IntegerType()),
    StructField("FXXH", IntegerType()),
    StructField("TG", IntegerType()),
    StructField("TN", IntegerType()),
    StructField("TNH", IntegerType()),
    StructField("TX", IntegerType()),
    StructField("TXH", IntegerType()),
    StructField("T10N", IntegerType()),
    StructField("T10NH", IntegerType()),
    StructField("SQ", IntegerType()),
    StructField("SP", IntegerType()),
    StructField("Q", IntegerType()),
    StructField("DR", IntegerType()),
    StructField("RH", IntegerType()),
    StructField("RHX", IntegerType()),
    StructField("RHXH", IntegerType()),
    StructField("EV24", IntegerType()),
    StructField("PG", IntegerType()),
    StructField("PX", IntegerType()),
    StructField("PXH", IntegerType()),
    StructField("PN", IntegerType()),
    StructField("PNH", IntegerType()),
    StructField("VVN", IntegerType()),
    StructField("VVNH", IntegerType()),
    StructField("VVX", IntegerType()),
    StructField("VVXH", IntegerType()),
    StructField("NG", IntegerType()),
    StructField("UG", IntegerType()),
    StructField("UX", IntegerType()),
    StructField("UXH", IntegerType()),
    StructField("UN", IntegerType()),
    StructField("UNH", IntegerType())
])
