from pyspark.sql.types import StructType, StructField
from pyspark.sql.types import DoubleType, IntegerType, StringType, DateType

schema = StructType([
    StructField("STN",			 DoubleType()),
    StructField("YYYYMMDD",		 IntegerType()),
    StructField("DDVEC",		 DoubleType()),
    StructField("FHVEC",		 DoubleType()),
    StructField("FG",			 DoubleType()),
    StructField("FHX",		 DoubleType()),
    StructField("FHXH",		 DoubleType()),
    StructField("FHN",		 DoubleType()),
    StructField("FHNH",		 DoubleType()),
    StructField("FXX",		 StringType()),
    StructField("FXXH",		 StringType()),
    StructField("TG",			 DoubleType()),
    StructField("TN",			 DoubleType()),
    StructField("TNH",		 DoubleType()),
    StructField("TX",			 DoubleType()),
    StructField("TXH",		 DoubleType()),
    StructField("T10N",		 DoubleType()),
    StructField("T10NH",		 StringType()),
    StructField("SQ",			 DoubleType()),
    StructField("SP",			 DoubleType()),
    StructField("Q",			 DoubleType()),
    StructField("DR",			 DoubleType()),
    StructField("RH",			 DoubleType()),
    StructField("RHX",		 DoubleType()),
    StructField("RHXH",		 StringType()),
    StructField("EV24",		 DoubleType()),
    StructField("PG",			 IntegerType()),
    StructField("PX",			 IntegerType()),
    StructField("PXH",		 StringType()),
    StructField("PN",			 IntegerType()),
    StructField("PNH",		 StringType()),
    StructField("VVN",		 DoubleType()),
    StructField("VVNH",		 DoubleType()),
    StructField("VVX",		 DoubleType()),
    StructField("VVXH",		 DoubleType()),
    StructField("NG",			 DoubleType()),
    StructField("UG",			 DoubleType()),
    StructField("UX",			 DoubleType()),
    StructField("UXH",		 DoubleType()),
    StructField("UN",			 DoubleType()),
    StructField("UNH",		 DoubleType())
])

# schema = StructType([
#     StructField("STN", StringType()),
#     StructField("YYYYMMDD", StringType()),
#     StructField("DDVEC", StringType()),
#     StructField("FHVEC", StringType()),
#     StructField("FG", StringType()),
#     StructField("FHX", StringType()),
#     StructField("FHXH", StringType()),
#     StructField("FHN", StringType()),
#     StructField("FHNH", StringType()),
#     StructField("FXX", StringType()),
#     StructField("FXXH", StringType()),
#     StructField("TG", StringType()),
#     StructField("TN", StringType()),
#     StructField("TNH", StringType()),
#     StructField("TX", StringType()),
#     StructField("TXH", StringType()),
#     StructField("T10N", StringType()),
#     StructField("T10NH", StringType()),
#     StructField("SQ", StringType()),
#     StructField("SP", StringType()),
#     StructField("Q", StringType()),
#     StructField("DR", StringType()),
#     StructField("RH", StringType()),
#     StructField("RHX", StringType()),
#     StructField("RHXH", StringType()),
#     StructField("EV24", StringType()),
#     StructField("PG", StringType()),
#     StructField("PX", StringType()),
#     StructField("PXH", StringType()),
#     StructField("PN", StringType()),
#     StructField("PNH", StringType()),
#     StructField("VVN", StringType()),
#     StructField("VVNH", StringType()),
#     StructField("VVX", StringType()),
#     StructField("VVXH", StringType()),
#     StructField("NG", StringType()),
#     StructField("UG", StringType()),
#     StructField("UX", StringType()),
#     StructField("UXH", StringType()),
#     StructField("UN", StringType()),
#     StructField("UNH", StringType())
# ])
