from pyspark.sql.types import StructType, StructField
from pyspark.sql.types import DoubleType, IntegerType, StringType, DateType

# schema = StructType([
#     StructField("STN", DoubleType(), nullable=True),
#     StructField("YYYYMMDD", IntegerType(), nullable=True),
#     StructField("DDVEC", DoubleType(), nullable=True),
#     StructField("FHVEC", DoubleType(), nullable=True),
#     StructField("FG", DoubleType(), nullable=True),
#     StructField("FHX", DoubleType(), nullable=True),
#     StructField("FHXH", DoubleType(), nullable=True),
#     StructField("FHN", DoubleType(), nullable=True),
#     StructField("FHNH", DoubleType(), nullable=True),
#     StructField("FXX", StringType(), nullable=True),
#     StructField("FXXH", StringType(), nullable=True),
#     StructField("TG", DoubleType(), nullable=True),
#     StructField("TN", DoubleType(), nullable=True),
#     StructField("TNH", DoubleType(), nullable=True),
#     StructField("TX", DoubleType(), nullable=True),
#     StructField("TXH", DoubleType(), nullable=True),
#     StructField("T10N", DoubleType(), nullable=True),
#     StructField("T10NH", StringType(), nullable=True),
#     StructField("SQ", DoubleType(), nullable=True),
#     StructField("SP", DoubleType(), nullable=True),
#     StructField("Q", DoubleType(), nullable=True),
#     StructField("DR", DoubleType(), nullable=True),
#     StructField("RH", DoubleType(), nullable=True),
#     StructField("RHX", DoubleType(), nullable=True),
#     StructField("RHXH", StringType(), nullable=True),
#     StructField("EV24", DoubleType(), nullable=True),
#     StructField("PG", IntegerType(), nullable=True),
#     StructField("PX", IntegerType(), nullable=True),
#     StructField("PXH", StringType(), nullable=True),
#     StructField("PN", IntegerType(), nullable=True),
#     StructField("PNH", StringType(), nullable=True),
#     StructField("VVN", DoubleType(), nullable=True),
#     StructField("VVNH", DoubleType(), nullable=True),
#     StructField("VVX", DoubleType(), nullable=True),
#     StructField("VVXH", DoubleType(), nullable=True),
#     StructField("NG", DoubleType(), nullable=True),
#     StructField("UG", DoubleType(), nullable=True),
#     StructField("UX", DoubleType(), nullable=True),
#     StructField("UXH", DoubleType(), nullable=True),
#     StructField("UN", DoubleType(), nullable=True),
#     StructField("UNH", DoubleType(), nullable=True)
# ])

schema = StructType([
    StructField("STN", IntegerType()),
    StructField("YYYYMMDD", DateType()),
    StructField("DDVEC", IntegerType()),
    StructField("FHVEC", IntegerType()),
    StructField("FG", IntegerType()),
    StructField("FHX", IntegerType()),
    StructField("FHXH", IntegerType()),
    StructField("FHN", IntegerType()),
    StructField("FHNH", IntegerType()),
    StructField("FXX", IntegerType()),
    StructField("FXXH", IntegerType()),
    StructField("TG", IntegerType()),
    StructField("TN", IntegerType()),
    StructField("TNH", IntegerType()),
    StructField("TX", IntegerType()),
    StructField("TXH", IntegerType()),
    StructField("T10N", IntegerType()),
    StructField("T10NH", IntegerType()),
    StructField("SQ", IntegerType()),
    StructField("SP", IntegerType()),
    StructField("Q", IntegerType()),
    StructField("DR", IntegerType()),
    StructField("RH", IntegerType()),
    StructField("RHX", IntegerType()),
    StructField("RHXH", IntegerType()),
    StructField("EV24", IntegerType()),
    StructField("PG", IntegerType()),
    StructField("PX", IntegerType()),
    StructField("PXH", IntegerType()),
    StructField("PN", IntegerType()),
    StructField("PNH", IntegerType()),
    StructField("VVN", IntegerType()),
    StructField("VVNH", IntegerType()),
    StructField("VVX", IntegerType()),
    StructField("VVXH", IntegerType()),
    StructField("NG", IntegerType()),
    StructField("UG", IntegerType()),
    StructField("UX", IntegerType()),
    StructField("UXH", IntegerType()),
    StructField("UN", IntegerType()),
    StructField("UNH", IntegerType())
])
